# Generated by Django 5.2.18 on 2026-10-06 19:04

import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pipeline_version', models.CharField(help_text='git describe of the code', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('seq_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pipeline_runs', to='samples.sequencingrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('FASTQ', 'FASTQ'), ('BAM', 'BAM'), ('BAI', 'BAM index'), ('CRAM', 'CRAM'), ('CRAI', 'CRAM index'), ('VCF', 'VCF'), ('TBI', 'Tabix index')], max_length=8)),
                ('path', models.CharField(max_length=1024)),
                ('bytes', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Enter a lowercase hex SHA-256.')])),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='runs.pipelinerun')),
            ],
            options={
                'ordering': ['run', 'kind', 'path'],
            },
        ),
        migrations.CreateModel(
            name='PipelineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('qc', 'FASTQ QC'), ('align', 'Align'), ('cram', 'CRAM'), ('call', 'Variant call'), ('load', 'Load variants')], max_length=32)),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('wall_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('max_rss_kb', models.PositiveBigIntegerField(blank=True, null=True)),
                ('stdout_tail', models.TextField(blank=True, default='')),
                ('stderr_tail', models.TextField(blank=True, default='')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='runs.pipelinerun')),
            ],
            options={
                'ordering': ['run', 'name', 'attempt'],
            },
        ),
        migrations.CreateModel(
            name='QcMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('fastq', 'FASTQ'), ('bam', 'BAM'), ('vcf', 'VCF')], max_length=8)),
                ('total_reads', models.BigIntegerField(blank=True, null=True)),
                ('total_bases', models.BigIntegerField(blank=True, null=True)),
                ('mean_len', models.FloatField(blank=True, null=True)),
                ('mean_qual', models.FloatField(blank=True, null=True)),
                ('gc_frac', models.FloatField(blank=True, null=True)),
                ('n_frac', models.FloatField(blank=True, null=True)),
                ('q20_frac', models.FloatField(blank=True, null=True)),
                ('q30_frac', models.FloatField(blank=True, null=True)),
                ('dup_frac_est', models.FloatField(blank=True, null=True)),
                ('mapped_frac', models.FloatField(blank=True, null=True)),
                ('mean_cov', models.FloatField(blank=True, null=True)),
                ('n_variants', models.IntegerField(blank=True, null=True)),
                ('ti_tv', models.FloatField(blank=True, null=True)),
                ('het_hom', models.FloatField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_metrics', to='runs.pipelinerun')),
            ],
            options={
                'ordering': ['run', 'stage'],
            },
        ),
        migrations.AddIndex(
            model_name='pipelinerun',
            index=models.Index(fields=['status', '-started_at'], name='pipelinerun_status_started'),
        ),
        migrations.AddIndex(
            model_name='pipelinerun',
            index=models.Index(condition=models.Q(('status', 'running')), fields=['seq_run'], name='pipelinerun_running_idx'),
        ),
        migrations.AddConstraint(
            model_name='pipelinerun',
            constraint=models.CheckConstraint(condition=models.Q(('finished_at__isnull', True), ('started_at__isnull', False), _connector='OR'), name='pipelinerun_finish_needs_start', violation_error_message='A run cannot finish before it started.'),
        ),
        migrations.AddConstraint(
            model_name='fileartifact',
            constraint=models.UniqueConstraint(fields=('run', 'kind', 'path'), name='fileartifact_unique_path'),
        ),
        migrations.AddConstraint(
            model_name='pipelinestep',
            constraint=models.UniqueConstraint(fields=('run', 'name', 'attempt'), name='pipelinestep_unique_attempt'),
        ),
        migrations.AddConstraint(
            model_name='pipelinestep',
            constraint=models.CheckConstraint(condition=models.Q(('attempt__gte', 1)), name='pipelinestep_attempt_positive'),
        ),
        migrations.AddIndex(
            model_name='qcmetric',
            index=django.contrib.postgres.indexes.GinIndex(fields=['details'], name='qcmetric_details_gin'),
        ),
        migrations.AddConstraint(
            model_name='qcmetric',
            constraint=models.UniqueConstraint(fields=('run', 'stage'), name='qcmetric_unique_stage'),
        ),
        migrations.AddConstraint(
            model_name='qcmetric',
            constraint=models.CheckConstraint(condition=models.Q(('gc_frac__isnull', True), models.Q(('gc_frac__gte', 0), ('gc_frac__lte', 1)), _connector='OR'), name='qcmetric_gc_frac_unit_interval', violation_error_message='gc_frac must be between 0 and 1.'),
        ),
        migrations.AddConstraint(
            model_name='qcmetric',
            constraint=models.CheckConstraint(condition=models.Q(('n_frac__isnull', True), models.Q(('n_frac__gte', 0), ('n_frac__lte', 1)), _connector='OR'), name='qcmetric_n_frac_unit_interval', violation_error_message='n_frac must be between 0 and 1.'),
        ),
        migrations.AddConstraint(
            model_name='qcmetric',
            constraint=models.CheckConstraint(condition=models.Q(('q20_frac__isnull', True), models.Q(('q20_frac__gte', 0), ('q20_frac__lte', 1)), _connector='OR'), name='qcmetric_q20_frac_unit_interval', violation_error_message='q20_frac must be between 0 and 1.'),
        ),
        migrations.AddConstraint(
            model_name='qcmetric',
            constraint=models.CheckConstraint(condition=models.Q(('q30_frac__isnull', True), models.Q(('q30_frac__gte', 0), ('q30_frac__lte', 1)), _connector='OR'), name='qcmetric_q30_frac_unit_interval', violation_error_message='q30_frac must be between 0 and 1.'),
        ),
        migrations.AddConstraint(
            model_name='qcmetric',
            constraint=models.CheckConstraint(condition=models.Q(('dup_frac_est__isnull', True), models.Q(('dup_frac_est__gte', 0), ('dup_frac_est__lte', 1)), _connector='OR'), name='qcmetric_dup_frac_est_unit_interval', violation_error_message='dup_frac_est must be between 0 and 1.'),
        ),
        migrations.AddConstraint(
            model_name='qcmetric',
            constraint=models.CheckConstraint(condition=models.Q(('mapped_frac__isnull', True), models.Q(('mapped_frac__gte', 0), ('mapped_frac__lte', 1)), _connector='OR'), name='qcmetric_mapped_frac_unit_interval', violation_error_message='mapped_frac must be between 0 and 1.'),
        ),
    ]
