# Generated by Django 5.2.18 on 2026-10-06 19:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=64, unique=True)),
                ('organism', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['external_id'],
            },
        ),
        migrations.CreateModel(
            name='SequencingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('ILLUMINA', 'Illumina'), ('ONT', 'Oxford Nanopore'), ('PACBIO', 'PacBio'), ('SIMULATED', 'Simulated')], max_length=16)),
                ('read_layout', models.CharField(choices=[('SE', 'Single-end'), ('PE', 'Paired-end')], max_length=2)),
                ('fastq_r1', models.CharField(max_length=1024)),
                ('fastq_r2', models.CharField(blank=True, default='', max_length=1024)),
                ('fastq_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Enter a lowercase hex SHA-256.')])),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sequencing_runs', to='samples.sample')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('sample', 'fastq_sha256'), name='sequencingrun_unique_sample_fastq'), models.CheckConstraint(condition=models.Q(models.Q(('read_layout', 'PE'), models.Q(('fastq_r2', ''), _negated=True)), models.Q(('read_layout', 'SE'), ('fastq_r2', '')), _connector='OR'), name='sequencingrun_layout_matches_files', violation_error_message='Paired-end runs need fastq_r2; single-end runs must not have one.')],
            },
        ),
    ]
